# Pandas letem světem

[10 minutový úvod](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html)

[Srovnání s jinými nástrojí (R, SQL, SAS)](https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/index.html)

## Data

Budeme používat [data o ceně nemovitostí z Kaggle](https://www.kaggle.com/alphaepsilon/housing-prices-dataset).
Máte 2 soubory: data [`housing.csv`](housing.csv) a popis dat [`housing_description.txt`](housing_description.txt).

## Načtení dat

Nejčastěji budeme používat funkci [`read_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html), ale existují i [dálší funkce](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html).

Výhodou pandas je, že vstupem může být jak soubor, tak i URL.

In [1]:
# Načteme pandas jako zkratku 'pd'
import pandas as pd

In [2]:
houses = pd.read_csv('housing.csv')
# Head zobrazi prvních 5 řádků, číslo lze změnit
houses.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## Výběr sloupců

Obecný postup (platí pro všechny názvy sloupců)

```python
houses['SalePrice']
```

Postup pro sloupce neobsahující mezery, výhoda: doplnění názvu sloupce tabulátorem

```python
houses.SalePrice
```

In [3]:
houses['SalePrice'].head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [4]:
houses.SalePrice.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

## Základní datové typy v Pandas

- `DataFrame` - tabulka s indexovanými řádky
- `Series` - sloupec s indexovanými řádky

Dále každá `Series` může být:

- Číslo (`int64`, `int32`, `float64`, `float32`)
- True/False (`bool`)
- Řetězec (`object`)
- Kategorie (`category`)
- Datum (`datetime64`)

Více v [tomto článku](https://pbpython.com/pandas_dtypes.html)

In [5]:
# Funkce pro určování datového typy ze základního Pythonu
type(houses)

pandas.core.frame.DataFrame

In [6]:
type(houses.SalePrice)

pandas.core.series.Series

In [7]:
# Zjistíme datové typy jednotlivých sloupců
houses.dtypes.head()

Id               int64
MSSubClass       int64
MSZoning        object
LotFrontage    float64
LotArea          int64
dtype: object

## Atributy versus metody

Dle názvu rozdíl ne vždy zřetelný, obecně atribut je něco, co není potřeba vypočitávat (sloupce, index, ale i dimenze).

Metoda se vola jako v základním pythonu se závorkami (např. `houses.head()`), zatímco atribut se volá bez závorek (např. `houses.columns`).

[Seznam atributů a metod `DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)

[Seznam atributů a metod `Series`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html)

In [8]:
houses.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [9]:
houses.shape

(1460, 81)

In [10]:
houses.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [11]:
# Popisná statistika, include='all' vytvoří statistiku i pro nenumerické sloupce
houses.describe(include='all')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460,1201.000000,1460.000000,1460,91,1460,1460,1460,...,1460.000000,7,281,54,1460.000000,1460.000000,1460.000000,1460,1460,1460.000000
unique,NaN,NaN,5,NaN,NaN,2,2,4,4,2,...,NaN,3,4,4,NaN,NaN,NaN,9,6,NaN
top,NaN,NaN,RL,NaN,NaN,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,Gd,MnPrv,Shed,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,NaN,1151,NaN,NaN,1454,50,925,1311,1459,...,NaN,3,157,49,NaN,NaN,NaN,1267,1198,NaN
mean,730.500000,56.897260,NaN,70.049958,10516.828082,NaN,NaN,NaN,NaN,NaN,...,2.758904,NaN,NaN,NaN,43.489041,6.321918,2007.815753,NaN,NaN,180921.195890
std,421.610009,42.300571,NaN,24.284752,9981.264932,NaN,NaN,NaN,NaN,NaN,...,40.177307,NaN,NaN,NaN,496.123024,2.703626,1.328095,NaN,NaN,79442.502883
min,1.000000,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,365.750000,20.000000,NaN,59.000000,7553.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,5.000000,2007.000000,NaN,NaN,129975.000000
50%,730.500000,50.000000,NaN,69.000000,9478.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,1095.250000,70.000000,NaN,80.000000,11601.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,1460.000000,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,...,738.000000,NaN,NaN,NaN,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [12]:
# Zjistit datový typ
houses.SalePrice.dtype

dtype('int64')

In [13]:
# Zkontrolovat zda Series obsahuje alespoň jednu chybějící hodnotu
houses.SalePrice.isnull().any()

False

## Operace se sloupci

- Vektorové operace se sloupci jsou rychlé
    - Sloupce lze sčítat, násobit, dělit, atd.
    - Příklad `houses.LotArea*0.09290304`
- Na téměř všechno, co chcete v pandas se sloupci udělat, už je metoda 😉

In [14]:
# Převedení čtverečních stop na metry čtvereční
houses.LotArea*0.09290304

0        785.030688
1        891.869184
2       1045.159200
3        887.224032
4       1324.797350
5       1311.326410
6        936.834255
7        964.519361
8        568.566605
9        689.340557
10      1040.514048
11      1107.775849
12      1204.766623
13       989.603182
14      1014.501197
15       568.566605
16      1044.323073
17      1002.516705
18      1272.307133
19       702.346982
20      1320.616714
21       692.034745
22       905.061416
23       392.422441
24       766.078468
25      1322.010259
26       668.901888
27      1066.341093
28      1516.270516
29       587.518825
           ...
1430    2037.363667
1431     457.826181
1432    1003.352832
1433     953.278093
1434    1616.512896
1435     780.385536
1436     836.127360
1437    1156.085430
1438     688.132817
1439    1076.188815
1440    1070.800439
1441     411.188855
1442    1022.212149
1443     822.563516
1444     789.675840
1445     780.385536
1446    2428.671272
1447     929.030400
1448    1093.190072
1449     142.420360
1450     836.127360
1451     860.467956
1452     341.418672
1453    1599.511640
1454     696.772800
1455     735.513368
1456    1223.997552
1457     840.029288
1458     902.738840
1459     923.177508
Name: LotArea, Length: 1460, dtype: float64

In [15]:
# Vytvoříme nový sloupec
houses['LotAreaMeters'] = houses.LotArea/0.09290304

In [16]:
houses.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotAreaMeters
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,90955.043021
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,103333.540000
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,121093.992188
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,102795.344480
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,153493.362542

## Filtrování
```
data[podmínka]

data[(podmínka1) & (podmínka2)]
```
Povolené operátory

- `&` logické AND
- `|` logické OR
- `~` logické NOT

Příklady
```python
houses[houses.SalePrice < 100000]

houses[(houses.SalePrice < 100000) & (houses.OverallCond >= 8)]
```

In [17]:
# Domy, které se prodali za méně než 100000 USD
houses[houses.SalePrice < 100000]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotAreaMeters
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,Shed,500,10,2006,WD,Normal,90000,116153.357307
29,30,30,RM,60.0,6324,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2008,WD,Normal,68500,68070.969475
30,31,70,C (all),50.0,8500,Pave,Pave,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,7,2008,WD,Normal,40000,91493.238542
39,40,90,RL,65.0,6040,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2008,WD,AdjLand,82000,65014.018917
68,69,30,RM,47.0,4608,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2010,WD,Normal,80000,49600.099200
75,76,180,RM,21.0,1596,Pave,NaN,Reg,Lvl,AllPub,...,NaN,GdWo,NaN,0,11,2009,WD,Normal,91000,17179.201025
88,89,50,C (all),105.0,8470,Pave,NaN,IR1,Lvl,AllPub,...,NaN,MnPrv,NaN,0,10,2009,ConLD,Abnorml,85000,91170.321230
91,92,20,RL,85.0,8500,Pave,NaN,Reg,Lvl,AllPub,...,NaN,GdWo,NaN,0,12,2006,WD,Abnorml,98600,91493.238542
97,98,20,RL,73.0,10921,Pave,NaN,Reg,HLS,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,94750,117552.665661
98,99,30,RL,85.0,10625,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,Shed,400,5,2010,COD,Abnorml,83000,114366.548178
125,126,190,RM,60.0,6780,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2006,WD,Normal,84500,72979.312625
127,128,45,RM,55.0,4388,Pave,NaN,IR1,Bnk,AllPub,...,NaN,NaN,NaN,0,6,2007,WD,Normal,87000,47232.038909
155,156,50,RL,60.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2008,WD,Normal,79000,103333.540000
210,211,30,RL,67.0,5604,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2008,WD,Normal,98000,60320.953975
223,224,20,RL,70.0,10500,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,3,2009,WD,Abnorml,97000,113021.059375
232,233,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2006,WD,Normal,94500,18083.369500
235,236,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2008,WD,Normal,89500,18083.369500
242,243,50,RM,63.0,5000,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2006,WD,Normal,79000,53819.552084
250,251,30,RL,55.0,5350,Pave,NaN,IR1,Lvl,AllPub,...,NaN,GdWo,Shed,450,5,2010,WD,Normal,76500,57586.920729
259,260,20,RM,70.0,12702,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,97000,136723.190113
264,265,30,RM,30.0,5232,Pave,Grvl,IR3,Bnk,AllPub,...,NaN,NaN,NaN,0,6,2008,WD,Normal,73000,56316.779300
287,288,20,RL,NaN,8125,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2006,WD,Normal,88000,87456.772136
307,308,50,RM,NaN,7920,Pave,Grvl,IR1,Lvl,AllPub,...,NaN,MnPrv,NaN,0,3,2008,WD,Normal,89500,85250.170500
308,309,30,RL,NaN,12342,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,3,2009,WD,Normal,82500,132848.182363
325,326,45,RM,50.0,5000,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2007,WD,Normal,87000,53819.552084
329,330,70,RM,60.0,6402,Pave,NaN,Reg,Lvl,AllPub,...,NaN,GdWo,NaN,0,7,2009,WD,Normal,78000,68910.554488
341,342,20,RH,60.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2009,WD,Normal,82000,90416.847500
342,343,90,RL,NaN,8544,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2006,WD,Normal,87500,91966.850600
344,345,160,RM,36.0,2592,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2010,WD,Normal,85000,27900.055800
352,353,50,RL,60.0,9084,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,3,2008,ConLw,Normal,95000,97779.362225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,1040,180,RM,21.0,1477,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2009,WD,Normal,80000,15898.295685
1049,1050,20,RL,60.0,11100,Pave,NaN,Reg,Low,AllPub,...,NaN,NaN,NaN,0,4,2010,WD,Abnorml,84900,119479.405625
1061,1062,30,C (all),120.0,18000,Grvl,NaN,Reg,Low,AllPub,...,NaN,NaN,Shed,560,8,2008,ConLD,Normal,81000,193750.387501
1062,1063,190,RM,85.0,13600,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2007,WD,Normal,90000,146389.181667
1072,1073,50,RL,50.0,7585,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2006,WD,Normal,91500,81644.260511
1086,1087,160,RM,NaN,1974,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2010,WD,Normal,83500,21247.959163
1090,1091,90,RL,60.0,8544,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2009,WD,Normal,92900,91966.850600
1100,1101,30,RL,60.0,8400,Pave,NaN,Reg,Bnk,AllPub,...,NaN,NaN,NaN,0,1,2009,WD,Normal,60000,90416.847500
1131,1132,20,RL,63.0,10712,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,9,2007,Oth,Abnorml,93500,115303.008384
1137,1138,50,RL,54.0,6342,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2010,WD,Normal,94000,68264.719863
1143,1144,20,RL,NaN,9000,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2008,WD,Normal,80000,96875.193750
1144,1145,190,RL,60.0,12180,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,7,2010,WD,Normal,80000,131104.428876
1179,1180,20,RL,77.0,8335,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2006,WD,Normal,93000,89717.193323
1186,1187,190,RL,107.0,10615,Pave,NaN,IR1,Bnk,AllPub,...,NaN,NaN,NaN,0,8,2009,WD,Abnorml,95000,114258.909073
1218,1219,50,RM,52.0,6240,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2006,WD,Normal,80500,67166.801000
1219,1220,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2006,WD,Abnorml,91500,18083.369500
1257,1258,30,RL,56.0,4060,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2009,WD,Normal,99900,43701.476292
1279,1280,50,C (all),60.0,7500,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2010,COD,Abnorml,68400,80729.328125
1321,1322,20,RL,NaN,6627,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2008,WD,Normal,72500,71332.434332
1323,1324,30,RL,50.0,5330,Pave,NaN,Reg,HLS,AllPub,...,NaN,NaN,NaN,0,12,2009,WD,Normal,82500,57371.642521
1325,1326,30,RM,40.0,3636,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,1,2008,WD,Normal,55000,39137.578275
1326,1327,30,RH,70.0,4270,Pave,NaN,Reg,Bnk,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,79000,45961.897479
1337,1338,30,RM,153.0,4118,Pave,Grvl,IR1,Bnk,AllPub,...,NaN,NaN,NaN,0,3,2006,WD,Normal,52500,44325.783096
1376,1377,30,RL,52.0,6292,Pave,NaN,Reg,Bnk,AllPub,...,NaN,NaN,NaN,0,4,2008,WD,Normal,91000,67726.524342
1378,1379,160,RM,21.0,1953,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2006,WD,Normal,83000,21021.917044
1380,1381,30,RL,45.0,8212,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2010,WD,Normal,58500,88393.232342
1412,1413,90,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2009,WD,Normal,90000,77500.155000
1432,1433,30,RL,60.0,10800,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2007,WD,Normal,64500,116250.232500
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000,16501.074669
1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500,185322.245644

In [18]:
# Domy, které se prodali za méně než 100000 USD a zároveň mají velmi dobrý nebo výborný stav
houses[(houses.SalePrice < 100000) & (houses.OverallCond >= 8)]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotAreaMeters
125,126,190,RM,60.0,6780,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2006,WD,Normal,84500,72979.312625
489,490,180,RM,21.0,1526,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2009,WD,Normal,86000,16425.727296
494,495,30,RM,50.0,5784,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2009,WD,Normal,91300,62258.457850
1137,1138,50,RL,54.0,6342,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2010,WD,Normal,94000,68264.719863
1257,1258,30,RL,56.0,4060,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2009,WD,Normal,99900,43701.476292

## Cvíčení

Vyberte domy, které splňuji všechny podmínky:
- Mají plochu pozemku více než 1000 metrů čtverečních (`LotAreaMeters`)
- Pozemek je pravidelného tvaru (`LotShape`)
- Rok vystavby je nejříve 2000 (`YearBuilt`)
- Cena je maximálně 150000 USD (`SalePrice`)

Kolik je domů, které splňují všechny podmínky?

Kolik je domů, které splňují alespoň jednu podmínku?

## Agregace dat

Použijeme metody `groupby`, která seskupí řádky dle jednoho nebo více sloupců a vrátí iterator.

Na tento iterátor potom aplikujeme nějakou metodu (count, mean, sum).
Pokud chceme aplikovat více metod nebo máme vlastní funkci, použijeme metodu `agg`.

```python
houses.groupby('LotShape').SalePrice.mean()

houses.groupby(['LotShape', 'OverallCond']).SalePrice.mean()
```

[Dokumentace groupby](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html)

In [19]:
# Zjistíme cenu nemovitostí dle tvaru pozemku
houses.groupby('LotShape').SalePrice.mean()

LotShape
IR1    206101.665289
IR2    239833.365854
IR3    216036.500000
Reg    164754.818378
Name: SalePrice, dtype: float64

In [20]:
# Zjistíme průmernou cenu nemovitostí dle tvaru pozemku a celkového stavu
houses.groupby(['LotShape', 'OverallCond']).SalePrice.mean()

LotShape  OverallCond
IR1       1               61000.000000
          2               80750.000000
          3              136656.000000
          4              116488.888889
          5              226462.943144
          6              174803.602740
          7              176484.271429
          8              178263.157895
          9              245957.142857
IR2       5              234471.310345
          6              190000.000000
          7              295875.000000
          8              212500.000000
          9              475000.000000
IR3       3              163500.000000
          5              221873.888889
Reg       2              182810.666667
          3               91905.550000
          4              121178.979167
          5              186517.900826
          6              144181.942529
          7              144140.656489
          8              144998.529412
          9              182528.571429
Name: SalePrice, dtype: float64

In [21]:
# Zjistíme průmernou cenu nemovitostí dle tvaru pozemku a celkového stavu 
# a zároveň počet nemovitosti v každé kategorii
houses.groupby(['LotShape', 'OverallCond']).SalePrice.agg(['mean', 'count'])

                               mean  count
LotShape OverallCond
IR1      1             61000.000000      1
         2             80750.000000      2
         3            136656.000000      4
         4            116488.888889      9
         5            226462.943144    299
         6            174803.602740     73
         7            176484.271429     70
         8            178263.157895     19
         9            245957.142857      7
IR2      5            234471.310345     29
         6            190000.000000      5
         7            295875.000000      4
         8            212500.000000      2
         9            475000.000000      1
IR3      3            163500.000000      1
         5            221873.888889      9
Reg      2            182810.666667      3
         3             91905.550000     20
         4            121178.979167     48
         5            186517.900826    484
         6            144181.942529    174
         7            144140.656489    131
         8            144998.529412     51
         9            182528.571429     14

## Cvíčení

Seskupte řádky dle druhu střechy (`RoofStyle`) a stavu exteriéru (`ExterCond`) a zobrazte minimální a maximální cenu a počet nemovitostí.

## Iterace řádky

Iterujeme `DataFrame` pomocí metody [`iterrows`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iterrows.html), která vrací n-tici (první prvek číslo řádku, druhý prvek - obsah řádku). Hodí se například pro tvorbu popisků ke grafům.

In [22]:
text = []
for i, row in houses.iterrows():
    # :.0f uloží číslo bez desetinného místa
    text.append('Cena (USD): {:.0f}, Plocha (m^2): {:.0f}'.format(row.SalePrice, row.LotAreaMeters))
text

['Cena (USD): 208500, Plocha (m^2): 90955',
 'Cena (USD): 181500, Plocha (m^2): 103334',
 'Cena (USD): 223500, Plocha (m^2): 121094',
 'Cena (USD): 140000, Plocha (m^2): 102795',
 'Cena (USD): 250000, Plocha (m^2): 153493',
 'Cena (USD): 143000, Plocha (m^2): 151933',
 'Cena (USD): 307000, Plocha (m^2): 108543',
 'Cena (USD): 200000, Plocha (m^2): 111751',
 'Cena (USD): 129900, Plocha (m^2): 65875',
 'Cena (USD): 118000, Plocha (m^2): 79868',
 'Cena (USD): 129500, Plocha (m^2): 120556',
 'Cena (USD): 345000, Plocha (m^2): 128349',
 'Cena (USD): 144000, Plocha (m^2): 139586',
 'Cena (USD): 279500, Plocha (m^2): 114657',
 'Cena (USD): 157000, Plocha (m^2): 117542',
 'Cena (USD): 132000, Plocha (m^2): 65875',
 'Cena (USD): 149000, Plocha (m^2): 120997',
 'Cena (USD): 90000, Plocha (m^2): 116153',
 'Cena (USD): 159000, Plocha (m^2): 147412',
 'Cena (USD): 139000, Plocha (m^2): 81375',
 'Cena (USD): 325300, Plocha (m^2): 153009',
 'Cena (USD): 139400, Plocha (m^2): 80180',
 'Cena (USD): 230000, Plocha (m^2): 104862',
 'Cena (USD): 129900, Plocha (m^2): 45467',
 'Cena (USD): 154000, Plocha (m^2): 88759',
 'Cena (USD): 256300, Plocha (m^2): 153170',
 'Cena (USD): 134800, Plocha (m^2): 77500',
 'Cena (USD): 306000, Plocha (m^2): 123548',
 'Cena (USD): 207500, Plocha (m^2): 175678',
 'Cena (USD): 68500, Plocha (m^2): 68071',
 'Cena (USD): 40000, Plocha (m^2): 91493',
 'Cena (USD): 149350, Plocha (m^2): 91967',
 'Cena (USD): 179900, Plocha (m^2): 118930',
 'Cena (USD): 165500, Plocha (m^2): 113581',
 'Cena (USD): 277500, Plocha (m^2): 78716',
 'Cena (USD): 309000, Plocha (m^2): 144430',
 'Cena (USD): 145000, Plocha (m^2): 116885',
 'Cena (USD): 153000, Plocha (m^2): 91838',
 'Cena (USD): 109000, Plocha (m^2): 85272',
 'Cena (USD): 82000, Plocha (m^2): 65014',
 'Cena (USD): 160000, Plocha (m^2): 93194',
 'Cena (USD): 170000, Plocha (m^2): 181964',
 'Cena (USD): 144000, Plocha (m^2): 98813',
 'Cena (USD): 130250, Plocha (m^2): 99028',
 'Cena (USD): 141000, Plocha (m^2): 85519',
 'Cena (USD): 319900, Plocha (m^2): 82430',
 'Cena (USD): 239686, Plocha (m^2): 138015',
 'Cena (USD): 249700, Plocha (m^2): 119436',
 'Cena (USD): 113000, Plocha (m^2): 47964',
 'Cena (USD): 127000, Plocha (m^2): 83334',
 'Cena (USD): 177000, Plocha (m^2): 149285',
 'Cena (USD): 114500, Plocha (m^2): 67167',
 'Cena (USD): 110000, Plocha (m^2): 91192',
 'Cena (USD): 385000, Plocha (m^2): 541113',
 'Cena (USD): 130000, Plocha (m^2): 76790',
 'Cena (USD): 180500, Plocha (m^2): 109523',
 'Cena (USD): 172500, Plocha (m^2): 28471',
 'Cena (USD): 196500, Plocha (m^2): 125346',
 'Cena (USD): 438780, Plocha (m^2): 147272',
 'Cena (USD): 124900, Plocha (m^2): 77500',
 'Cena (USD): 158000, Plocha (m^2): 140706',
 'Cena (USD): 101000, Plocha (m^2): 77500',
 'Cena (USD): 202500, Plocha (m^2): 69341',
 'Cena (USD): 140000, Plocha (m^2): 110868',
 'Cena (USD): 219500, Plocha (m^2): 100912',
 'Cena (USD): 317000, Plocha (m^2): 103237',
 'Cena (USD): 180000, Plocha (m^2): 214202',
 'Cena (USD): 226000, Plocha (m^2): 114797',
 'Cena (USD): 80000, Plocha (m^2): 49600',
 'Cena (USD): 225000, Plocha (m^2): 167842',
 'Cena (USD): 244000, Plocha (m^2): 146938',
 'Cena (USD): 129500, Plocha (m^2): 81795',
 'Cena (USD): 185000, Plocha (m^2): 109157',
 'Cena (USD): 144900, Plocha (m^2): 109792',
 'Cena (USD): 107400, Plocha (m^2): 62323',
 'Cena (USD): 91000, Plocha (m^2): 17179',
 'Cena (USD): 135750, Plocha (m^2): 91224',
 'Cena (USD): 127000, Plocha (m^2): 92946',
 'Cena (USD): 136500, Plocha (m^2): 116013',
 'Cena (USD): 110000, Plocha (m^2): 112375',
 'Cena (USD): 193500, Plocha (m^2): 139931',
 'Cena (USD): 153500, Plocha (m^2): 48438',
 'Cena (USD): 245000, Plocha (m^2): 109856',
 'Cena (USD): 126500, Plocha (m^2): 95713',
 'Cena (USD): 168500, Plocha (m^2): 91816',
 'Cena (USD): 260000, Plocha (m^2): 172858',
 'Cena (USD): 174000, Plocha (m^2): 128209',
 'Cena (USD): 164500, Plocha (m^2): 42528',
 'Cena (USD): 85000, Plocha (m^2): 91170',
 'Cena (USD): 123600, Plocha (m^2): 86865',
 'Cena (USD): 109900, Plocha (m^2): 77500',
 'Cena (USD): 98600, Plocha (m^2): 91493',
 'Cena (USD): 163500, Plocha (m^2): 143806',
 'Cena (USD): 133900, Plocha (m^2): 77500',
 'Cena (USD): 204750, Plocha (m^2): 100503',
 'Cena (USD): 185000, Plocha (m^2): 105110',
 'Cena (USD): 214000, Plocha (m^2): 110481',
 'Cena (USD): 94750, Plocha (m^2): 117553',
 'Cena (USD): 83000, Plocha (m^2): 114367',
 'Cena (USD): 128950, Plocha (m^2): 100320',
 'Cena (USD): 205000, Plocha (m^2): 114130',
 'Cena (USD): 178000, Plocha (m^2): 99093',
 'Cena (USD): 118964, Plocha (m^2): 75541',
 'Cena (USD): 198900, Plocha (m^2): 111966',
 'Cena (USD): 169500, Plocha (m^2): 83506',
 'Cena (USD): 250000, Plocha (m^2): 100912',
 'Cena (USD): 100000, Plocha (m^2): 116250',
 'Cena (USD): 115000, Plocha (m^2): 64583',
 'Cena (USD): 115000, Plocha (m^2): 91493',
 'Cena (USD): 190000, Plocha (m^2): 126487',
 'Cena (USD): 136900, Plocha (m^2): 102526',
 'Cena (USD): 180000, Plocha (m^2): 83420',
 'Cena (USD): 383970, Plocha (m^2): 107262',
 'Cena (USD): 217000, Plocha (m^2): 226042',
 'Cena (USD): 259500, Plocha (m^2): 78135',
 'Cena (USD): 176000, Plocha (m^2): 34767',
 'Cena (USD): 139000, Plocha (m^2): 125034',
 'Cena (USD): 155000, Plocha (m^2): 91881',
 'Cena (USD): 320000, Plocha (m^2): 133214',
 'Cena (USD): 163990, Plocha (m^2): 91073',
 'Cena (USD): 180000, Plocha (m^2): 230918',
 'Cena (USD): 100000, Plocha (m^2): 65229',
 'Cena (USD): 136000, Plocha (m^2): 101870',
 'Cena (USD): 153900, Plocha (m^2): 84949',
 'Cena (USD): 181000, Plocha (m^2): 183449',
 'Cena (USD): 84500, Plocha (m^2): 72979',
 'Cena (USD): 128000, Plocha (m^2): 53045',
 'Cena (USD): 87000, Plocha (m^2): 47232',
 'Cena (USD): 155000, Plocha (m^2): 81698',
 'Cena (USD): 150000, Plocha (m^2): 96585',
 'Cena (USD): 226000, Plocha (m^2): 152848',
 'Cena (USD): 244000, Plocha (m^2): 131578',
 'Cena (USD): 150750, Plocha (m^2): 79524',
 'Cena (USD): 220000, Plocha (m^2): 73765',
 'Cena (USD): 180000, Plocha (m^2): 111245',
 'Cena (USD): 174000, Plocha (m^2): 111945',
 'Cena (USD): 143000, Plocha (m^2): 111460',
 'Cena (USD): 171000, Plocha (m^2): 119156',
 'Cena (USD): 230000, Plocha (m^2): 97586',
 'Cena (USD): 231500, Plocha (m^2): 166044',
 'Cena (USD): 115000, Plocha (m^2): 113021',
 'Cena (USD): 260000, Plocha (m^2): 125346',
 'Cena (USD): 166000, Plocha (m^2): 91709',
 'Cena (USD): 204000, Plocha (m^2): 111245',
 'Cena (USD): 125000, Plocha (m^2): 97952',
 'Cena (USD): 130000, Plocha (m^2): 27147',
 'Cena (USD): 105000, Plocha (m^2): 65875',
 'Cena (USD): 222500, Plocha (m^2): 102311',
 'Cena (USD): 141000, Plocha (m^2): 80729',
 'Cena (USD): 115000, Plocha (m^2): 67167',
 'Cena (USD): 122000, Plocha (m^2): 111471',
 'Cena (USD): 372402, Plocha (m^2): 149521',
 'Cena (USD): 190000, Plocha (m^2): 159338',
 'Cena (USD): 235000, Plocha (m^2): 145313',
 'Cena (USD): 125000, Plocha (m^2): 122063',
 'Cena (USD): 79000, Plocha (m^2): 103334',
 'Cena (USD): 109500, Plocha (m^2): 77500',
 'Cena (USD): 269500, Plocha (m^2): 129199',
 'Cena (USD): 254900, Plocha (m^2): 135109',
 'Cena (USD): 320000, Plocha (m^2): 208583',
 'Cena (USD): 162500, Plocha (m^2): 119695',
 'Cena (USD): 412500, Plocha (m^2): 147336',
 'Cena (USD): 220000, Plocha (m^2): 131126',
 'Cena (USD): 103200, Plocha (m^2): 59202',
 'Cena (USD): 152000, Plocha (m^2): 58125',
 'Cena (USD): 127500, Plocha (m^2): 108780',
 'Cena (USD): 190000, Plocha (m^2): 115260',
 'Cena (USD): 325624, Plocha (m^2): 113688',
 'Cena (USD): 183500, Plocha (m^2): 88738',
 'Cena (USD): 228000, Plocha (m^2): 179424',
 'Cena (USD): 128500, Plocha (m^2): 133020',
 'Cena (USD): 215000, Plocha (m^2): 341969',
 'Cena (USD): 239000, Plocha (m^2): 57113',
 'Cena (USD): 163000, Plocha (m^2): 109760',
 'Cena (USD): 184000, Plocha (m^2): 133645',
 'Cena (USD): 243000, Plocha (m^2): 135787',
 'Cena (USD): 211000, Plocha (m^2): 107951',
 'Cena (USD): 172500, Plocha (m^2): 146927',
 'Cena (USD): 501837, Plocha (m^2): 187540',
 'Cena (USD): 100000, Plocha (m^2): 91709',
 'Cena (USD): 177000, Plocha (m^2): 22787',
 'Cena (USD): 200100, Plocha (m^2): 81677',
 'Cena (USD): 120000, Plocha (m^2): 97521',
 'Cena (USD): 200000, Plocha (m^2): 122988',
 'Cena (USD): 127000, Plocha (m^2): 80062',
 'Cena (USD): 475000, Plocha (m^2): 247032',
 'Cena (USD): 173000, Plocha (m^2): 107069',
 'Cena (USD): 135000, Plocha (m^2): 112052',
 'Cena (USD): 153337, Plocha (m^2): 75541',
 'Cena (USD): 286000, Plocha (m^2): 52991',
 'Cena (USD): 315000, Plocha (m^2): 113775',
 'Cena (USD): 184000, Plocha (m^2): 80428',
 'Cena (USD): 192000, Plocha (m^2): 97058',
 'Cena (USD): 130000, Plocha (m^2): 27147',
 'Cena (USD): 127000, Plocha (m^2): 77285',
 'Cena (USD): 148500, Plocha (m^2): 24542',
 'Cena (USD): 311872, Plocha (m^2): 101353',
 'Cena (USD): 235000, Plocha (m^2): 273608',
 'Cena (USD): 104000, Plocha (m^2): 59417',
 'Cena (USD): 274900, Plocha (m^2): 103237',
 'Cena (USD): 140000, Plocha (m^2): 91988',
 'Cena (USD): 171500, Plocha (m^2): 108985',
 'Cena (USD): 112000, Plocha (m^2): 75347',
 'Cena (USD): 149000, Plocha (m^2): 47770',
 'Cena (USD): 110000, Plocha (m^2): 37674',
 'Cena (USD): 180500, Plocha (m^2): 127563',
 'Cena (USD): 143900, Plocha (m^2): 147175',
 'Cena (USD): 141000, Plocha (m^2): 134474',
 'Cena (USD): 277000, Plocha (m^2): 154613',
 'Cena (USD): 145000, Plocha (m^2): 88802',
 'Cena (USD): 98000, Plocha (m^2): 60321',
 'Cena (USD): 186000, Plocha (m^2): 112160',
 'Cena (USD): 252678, Plocha (m^2): 93000',
 'Cena (USD): 156000, Plocha (m^2): 146045',
 'Cena (USD): 161750, Plocha (m^2): 117327',
 'Cena (USD): 134450, Plocha (m^2): 107758',
 'Cena (USD): 210000, Plocha (m^2): 90955',
 'Cena (USD): 107000, Plocha (m^2): 106627',
 'Cena (USD): 311500, Plocha (m^2): 168563',
 'Cena (USD): 167240, Plocha (m^2): 32399',
 'Cena (USD): 204900, Plocha (m^2): 96768',
 'Cena (USD): 200000, Plocha (m^2): 86843',
 'Cena (USD): 179900, Plocha (m^2): 123516',
 'Cena (USD): 97000, Plocha (m^2): 113021',
 'Cena (USD): 386250, Plocha (m^2): 145011',
 'Cena (USD): 112000, Plocha (m^2): 18083',
 'Cena (USD): 290000, Plocha (m^2): 107101',
 'Cena (USD): 106000, Plocha (m^2): 20118',
 'Cena (USD): 125000, Plocha (m^2): 91719',
 'Cena (USD): 192500, Plocha (m^2): 34251',
 'Cena (USD): 148000, Plocha (m^2): 94292',
 'Cena (USD): 403000, Plocha (m^2): 162944',
 'Cena (USD): 94500, Plocha (m^2): 18083',
 'Cena (USD): 128200, Plocha (m^2): 114636',
 'Cena (USD): 216500, Plocha (m^2): 84507',
 'Cena (USD): 89500, Plocha (m^2): 18083',
 'Cena (USD): 185500, Plocha (m^2): 94432',
 'Cena (USD): 194500, Plocha (m^2): 101751',
 'Cena (USD): 318000, Plocha (m^2): 129490',
 'Cena (USD): 113000, Plocha (m^2): 94087',
 'Cena (USD): 262500, Plocha (m^2): 96875',
 'Cena (USD): 110500, Plocha (m^2): 41764',
 'Cena (USD): 79000, Plocha (m^2): 53820',
 'Cena (USD): 120000, Plocha (m^2): 115841',
 'Cena (USD): 205000, Plocha (m^2): 95584',
 'Cena (USD): 241500, Plocha (m^2): 111945',
 'Cena (USD): 137000, Plocha (m^2): 98404',
 'Cena (USD): 140000, Plocha (m^2): 121740',
 'Cena (USD): 180000, Plocha (m^2): 121815',
 'Cena (USD): 277000, Plocha (m^2): 1711462',
 'Cena (USD): 76500, Plocha (m^2): 57587',
 'Cena (USD): 235000, Plocha (m^2): 51129',
 'Cena (USD): 173000, Plocha (m^2): 90051',
 'Cena (USD): 158000, Plocha (m^2): 100643',
 'Cena (USD): 145000, Plocha (m^2): 90417',
 'Cena (USD): 230000, Plocha (m^2): 94055',
 'Cena (USD): 207500, Plocha (m^2): 94626',
 'Cena (USD): 220000, Plocha (m^2): 94873',
 'Cena (USD): 231500, Plocha (m^2): 133849',
 'Cena (USD): 97000, Plocha (m^2): 136723',
 'Cena (USD): 176000, Plocha (m^2): 207700',
 'Cena (USD): 276000, Plocha (m^2): 103204',
 'Cena (USD): 151000, Plocha (m^2): 91181',
 'Cena (USD): 130000, Plocha (m^2): 59202',
 'Cena (USD): 73000, Plocha (m^2): 56317',
 'Cena (USD): 175500, Plocha (m^2): 130136',
 'Cena (USD): 185000, Plocha (m^2): 120631',
 'Cena (USD): 179500, Plocha (m^2): 90417',
 'Cena (USD): 120500, Plocha (m^2): 74271',
 'Cena (USD): 148000, Plocha (m^2): 85218',
 'Cena (USD): 266000, Plocha (m^2): 115475',
 'Cena (USD): 241500, Plocha (m^2): 420912',
 'Cena (USD): 290000, Plocha (m^2): 126627',
 'Cena (USD): 139000, Plocha (m^2): 103334',
 'Cena (USD): 124500, Plocha (m^2): 89491',
 'Cena (USD): 205000, Plocha (m^2): 78189',
 'Cena (USD): 201000, Plocha (m^2): 98985',
 'Cena (USD): 141000, Plocha (m^2): 206000',
 'Cena (USD): 415298, Plocha (m^2): 155539',
 'Cena (USD): 192000, Plocha (m^2): 107693',
 'Cena (USD): 228500, Plocha (m^2): 121492',
 'Cena (USD): 185000, Plocha (m^2): 77500',
 'Cena (USD): 207500, Plocha (m^2): 54498',
 'Cena (USD): 244600, Plocha (m^2): 103463',
 'Cena (USD): 179200, Plocha (m^2): 86240',
 'Cena (USD): 164700, Plocha (m^2): 45757',
 'Cena (USD): 159000, Plocha (m^2): 105336',
 'Cena (USD): 88000, Plocha (m^2): 87457',
 'Cena (USD): 122000, Plocha (m^2): 105691',
 'Cena (USD): 153575, Plocha (m^2): 93969',
 'Cena (USD): 233230, Plocha (m^2): 168035',
 'Cena (USD): 135900, Plocha (m^2): 61214',
 'Cena (USD): 131000, Plocha (m^2): 122805',
 'Cena (USD): 235000, Plocha (m^2): 179316',
 'Cena (USD): 167000, Plocha (m^2): 103334',
 'Cena (USD): 142500, Plocha (m^2): 85433',
 'Cena (USD): 152000, Plocha (m^2): 147573',
 'Cena (USD): 239000, Plocha (m^2): 79642',
 'Cena (USD): 175000, Plocha (m^2): 125938',
 'Cena (USD): 158500, Plocha (m^2): 150695',
 'Cena (USD): 157000, Plocha (m^2): 169532',
 'Cena (USD): 267000, Plocha (m^2): 174655',
 'Cena (USD): 205000, Plocha (m^2): 147509',
 'Cena (USD): 149900, Plocha (m^2): 105486',
 'Cena (USD): 295000, Plocha (m^2): 197905',
 'Cena (USD): 305900, Plocha (m^2): 111794',
 'Cena (USD): 225000, Plocha (m^2): 145033',
 'Cena (USD): 89500, Plocha (m^2): 85250',
 'Cena (USD): 82500, Plocha (m^2): 132848',
 'Cena (USD): 360000, Plocha (m^2): 133236',
 'Cena (USD): 165600, Plocha (m^2): 82721',
 'Cena (USD): 132000, Plocha (m^2): 86111',
 'Cena (USD): 119900, Plocha (m^2): 83959',
 'Cena (USD): 375000, Plocha (m^2): 2316878',
 'Cena (USD): 178000, Plocha (m^2): 103334',
 'Cena (USD): 188500, Plocha (m^2): 83905',
 'Cena (USD): 260000, Plocha (m^2): 139985',
 'Cena (USD): 270000, Plocha (m^2): 96875',
 'Cena (USD): 260000, Plocha (m^2): 106563',
 'Cena (USD): 187500, Plocha (m^2): 151933',
 'Cena (USD): 342643, Plocha (m^2): 175010',
 'Cena (USD): 354000, Plocha (m^2): 130233',
 'Cena (USD): 301000, Plocha (m^2): 111729',
 'Cena (USD): 126175, Plocha (m^2): 62646',
 'Cena (USD): 242000, Plocha (m^2): 121363',
 'Cena (USD): 87000, Plocha (m^2): 53820',
 'Cena (USD): 324000, Plocha (m^2): 116745',
 'Cena (USD): 145250, Plocha (m^2): 124861',
 'Cena (USD): 214500, Plocha (m^2): 127961',
 'Cena (USD): 78000, Plocha (m^2): 68911',
 'Cena (USD): 119000, Plocha (m^2): 114356',
 'Cena (USD): 139000, Plocha (m^2): 88006',
 'Cena (USD): 284000, Plocha (m^2): 114689',
 'Cena (USD): 207000, Plocha (m^2): 88243',
 'Cena (USD): 192000, Plocha (m^2): 97327',
 'Cena (USD): 228950, Plocha (m^2): 1772385',
 'Cena (USD): 377426, Plocha (m^2): 152385',
 'Cena (USD): 214000, Plocha (m^2): 98328',
 'Cena (USD): 202500, Plocha (m^2): 152256',
 'Cena (USD): 155000, Plocha (m^2): 133472',
 'Cena (USD): 202900, Plocha (m^2): 152751',
 'Cena (USD): 82000, Plocha (m^2): 90417',
 'Cena (USD): 87500, Plocha (m^2): 91967',
 'Cena (USD): 266000, Plocha (m^2): 95250',
 'Cena (USD): 85000, Plocha (m^2): 27900',
 'Cena (USD): 140200, Plocha (m^2): 69266',
 'Cena (USD): 151500, Plocha (m^2): 137477',
 'Cena (USD): 157500, Plocha (m^2): 189445',
 'Cena (USD): 154000, Plocha (m^2): 26350',
 'Cena (USD): 437154, Plocha (m^2): 219917',
 'Cena (USD): 318061, Plocha (m^2): 84174',
 'Cena (USD): 190000, Plocha (m^2): 56737',
 'Cena (USD): 95000, Plocha (m^2): 97779',
 'Cena (USD): 105900, Plocha (m^2): 91709',
 'Cena (USD): 140000, Plocha (m^2): 90417',
 'Cena (USD): 177500, Plocha (m^2): 121083',
 'Cena (USD): 173000, Plocha (m^2): 99545',
 'Cena (USD): 134000, Plocha (m^2): 45467',
 'Cena (USD): 130000, Plocha (m^2): 74594',
 'Cena (USD): 280000, Plocha (m^2): 129285',
 'Cena (USD): 156000, Plocha (m^2): 81160',
 'Cena (USD): 145000, Plocha (m^2): 98425',
 'Cena (USD): 198500, Plocha (m^2): 78587',
 'Cena (USD): 118000, Plocha (m^2): 18083',
 'Cena (USD): 190000, Plocha (m^2): 202362',
 'Cena (USD): 147000, Plocha (m^2): 115066',
 'Cena (USD): 159000, Plocha (m^2): 102257',
 'Cena (USD): 165000, Plocha (m^2): 98490',
 'Cena (USD): 132000, Plocha (m^2): 83959',
 'Cena (USD): 162000, Plocha (m^2): 105809',
 'Cena (USD): 172400, Plocha (m^2): 87414',
 'Cena (USD): 134432, Plocha (m^2): 184278',
 'Cena (USD): 125000, Plocha (m^2): 77231',
 'Cena (USD): 123000, Plocha (m^2): 114463',
 'Cena (USD): 219500, Plocha (m^2): 88264',
 'Cena (USD): 61000, Plocha (m^2): 107854',
 'Cena (USD): 148000, Plocha (m^2): 95218',
 'Cena (USD): 340000, Plocha (m^2): 119942',
 'Cena (USD): 394432, Plocha (m^2): 122644',
 'Cena (USD): 179000, Plocha (m^2): 87435',
 'Cena (USD): 127000, Plocha (m^2): 53820',
 'Cena (USD): 187750, Plocha (m^2): 77500',
 'Cena (USD): 213500, Plocha (m^2): 99512',
 'Cena (USD): 76000, Plocha (m^2): 96875',
 'Cena (USD): 240000, Plocha (m^2): 571639',
 'Cena (USD): 192000, Plocha (m^2): 34251',
 'Cena (USD): 81000, Plocha (m^2): 90524',
 'Cena (USD): 125000, Plocha (m^2): 77500',
 'Cena (USD): 191000, Plocha (m^2): 100987',
 'Cena (USD): 426000, Plocha (m^2): 134269',
 'Cena (USD): 119000, Plocha (m^2): 90471',
 'Cena (USD): 215000, Plocha (m^2): 131417',
 'Cena (USD): 106500, Plocha (m^2): 89760',
 'Cena (USD): 100000, Plocha (m^2): 80148',
 'Cena (USD): 109000, Plocha (m^2): 109081',
 'Cena (USD): 129000, Plocha (m^2): 103021',
 'Cena (USD): 123000, Plocha (m^2): 77500',
 'Cena (USD): 169500, Plocha (m^2): 81698',
 'Cena (USD): 67000, Plocha (m^2): 96520',
 'Cena (USD): 241000, Plocha (m^2): 87457',
 'Cena (USD): 245500, Plocha (m^2): 161060',
 'Cena (USD): 164990, Plocha (m^2): 94367',
 'Cena (USD): 108000, Plocha (m^2): 109792',
 'Cena (USD): 258000, Plocha (m^2): 130136',
 'Cena (USD): 168000, Plocha (m^2): 111557',
 'Cena (USD): 150000, Plocha (m^2): 107542',
 'Cena (USD): 115000, Plocha (m^2): 112806',
 'Cena (USD): 177000, Plocha (m^2): 167659',
 'Cena (USD): 280000, Plocha (m^2): 152352',
 'Cena (USD): 339750, Plocha (m^2): 116250',
 'Cena (USD): 60000, Plocha (m^2): 103021',
 'Cena (USD): 145000, Plocha (m^2): 372969',
 'Cena (USD): 222000, Plocha (m^2): 47393',
 'Cena (USD): 115000, Plocha (m^2): 96445',
 'Cena (USD): 228000, Plocha (m^2): 120857',
 'Cena (USD): 181134, Plocha (m^2): 95788',
 'Cena (USD): 149500, Plocha (m^2): 84432',
 'Cena (USD): 239000, Plocha (m^2): 241327',
 'Cena (USD): 126000, Plocha (m^2): 87834',
 'Cena (USD): 142000, Plocha (m^2): 90955',
 'Cena (USD): 206300, Plocha (m^2): 75993',
 'Cena (USD): 215000, Plocha (m^2): 179058',
 'Cena (USD): 113000, Plocha (m^2): 234115',
 'Cena (USD): 315000, Plocha (m^2): 99028',
 'Cena (USD): 139000, Plocha (m^2): 96875',
 'Cena (USD): 135000, Plocha (m^2): 36360',
 'Cena (USD): 275000, Plocha (m^2): 137778',
 'Cena (USD): 109008, Plocha (m^2): 92494',
 'Cena (USD): 195400, Plocha (m^2): 72786',
 'Cena (USD): 175000, Plocha (m^2): 123322',
 'Cena (USD): 85400, Plocha (m^2): 18083',
 'Cena (USD): 79900, Plocha (m^2): 60127',
 'Cena (USD): 122500, Plocha (m^2): 20667',
 'Cena (USD): 181000, Plocha (m^2): 116670',
 'Cena (USD): 81000, Plocha (m^2): 20344',
 'Cena (USD): 212000, Plocha (m^2): 114819',
 'Cena (USD): 116000, Plocha (m^2): 47361',
 'Cena (USD): 119000, Plocha (m^2): 64583',
 'Cena (USD): 90350, Plocha (m^2): 46070',
 'Cena (USD): 110000, Plocha (m^2): 132977',
 'Cena (USD): 555000, Plocha (m^2): 166098',
 'Cena (USD): 118000, Plocha (m^2): 130329',
 'Cena (USD): 162900, Plocha (m^2): 67167',
 'Cena (USD): 172500, Plocha (m^2): 42216',
 'Cena (USD): 210000, Plocha (m^2): 94184',
 'Cena (USD): 127500, Plocha (m^2): 106078',
 'Cena (USD): 190000, Plocha (m^2): 177518',
 'Cena (USD): 199900, Plocha (m^2): 120706',
 'Cena (USD): 119500, Plocha (m^2): 92570',
 'Cena (USD): 120000, Plocha (m^2): 64583',

## Cvíčení

Vytvořte seznam, kde každý prvek bude ve formátu: `'Cena (CZK): {:.0f}, Plocha (m^2): {:.0f}'`.

Pro vytvoření ceny v korunách, počitejte s kurzem 22.55 CZK.

In [23]:
text = []
for i, row in houses.iterrows():
    text.append('Cena (CZK): {:.0f}, Plocha (m^2): {:.0f}'.format(row.SalePrice * 22.55, row.LotAreaMeters))
text

['Cena (CZK): 4701675, Plocha (m^2): 90955',
 'Cena (CZK): 4092825, Plocha (m^2): 103334',
 'Cena (CZK): 5039925, Plocha (m^2): 121094',
 'Cena (CZK): 3157000, Plocha (m^2): 102795',
 'Cena (CZK): 5637500, Plocha (m^2): 153493',
 'Cena (CZK): 3224650, Plocha (m^2): 151933',
 'Cena (CZK): 6922850, Plocha (m^2): 108543',
 'Cena (CZK): 4510000, Plocha (m^2): 111751',
 'Cena (CZK): 2929245, Plocha (m^2): 65875',
 'Cena (CZK): 2660900, Plocha (m^2): 79868',
 'Cena (CZK): 2920225, Plocha (m^2): 120556',
 'Cena (CZK): 7779750, Plocha (m^2): 128349',
 'Cena (CZK): 3247200, Plocha (m^2): 139586',
 'Cena (CZK): 6302725, Plocha (m^2): 114657',
 'Cena (CZK): 3540350, Plocha (m^2): 117542',
 'Cena (CZK): 2976600, Plocha (m^2): 65875',
 'Cena (CZK): 3359950, Plocha (m^2): 120997',
 'Cena (CZK): 2029500, Plocha (m^2): 116153',
 'Cena (CZK): 3585450, Plocha (m^2): 147412',
 'Cena (CZK): 3134450, Plocha (m^2): 81375',
 'Cena (CZK): 7335515, Plocha (m^2): 153009',
 'Cena (CZK): 3143470, Plocha (m^2): 80180',
 'Cena (CZK): 5186500, Plocha (m^2): 104862',
 'Cena (CZK): 2929245, Plocha (m^2): 45467',
 'Cena (CZK): 3472700, Plocha (m^2): 88759',
 'Cena (CZK): 5779565, Plocha (m^2): 153170',
 'Cena (CZK): 3039740, Plocha (m^2): 77500',
 'Cena (CZK): 6900300, Plocha (m^2): 123548',
 'Cena (CZK): 4679125, Plocha (m^2): 175678',
 'Cena (CZK): 1544675, Plocha (m^2): 68071',
 'Cena (CZK): 902000, Plocha (m^2): 91493',
 'Cena (CZK): 3367842, Plocha (m^2): 91967',
 'Cena (CZK): 4056745, Plocha (m^2): 118930',
 'Cena (CZK): 3732025, Plocha (m^2): 113581',
 'Cena (CZK): 6257625, Plocha (m^2): 78716',
 'Cena (CZK): 6967950, Plocha (m^2): 144430',
 'Cena (CZK): 3269750, Plocha (m^2): 116885',
 'Cena (CZK): 3450150, Plocha (m^2): 91838',
 'Cena (CZK): 2457950, Plocha (m^2): 85272',
 'Cena (CZK): 1849100, Plocha (m^2): 65014',
 'Cena (CZK): 3608000, Plocha (m^2): 93194',
 'Cena (CZK): 3833500, Plocha (m^2): 181964',
 'Cena (CZK): 3247200, Plocha (m^2): 98813',
 'Cena (CZK): 2937138, Plocha (m^2): 99028',
 'Cena (CZK): 3179550, Plocha (m^2): 85519',
 'Cena (CZK): 7213745, Plocha (m^2): 82430',
 'Cena (CZK): 5404919, Plocha (m^2): 138015',
 'Cena (CZK): 5630735, Plocha (m^2): 119436',
 'Cena (CZK): 2548150, Plocha (m^2): 47964',
 'Cena (CZK): 2863850, Plocha (m^2): 83334',
 'Cena (CZK): 3991350, Plocha (m^2): 149285',
 'Cena (CZK): 2581975, Plocha (m^2): 67167',
 'Cena (CZK): 2480500, Plocha (m^2): 91192',
 'Cena (CZK): 8681750, Plocha (m^2): 541113',
 'Cena (CZK): 2931500, Plocha (m^2): 76790',
 'Cena (CZK): 4070275, Plocha (m^2): 109523',
 'Cena (CZK): 3889875, Plocha (m^2): 28471',
 'Cena (CZK): 4431075, Plocha (m^2): 125346',
 'Cena (CZK): 9894489, Plocha (m^2): 147272',
 'Cena (CZK): 2816495, Plocha (m^2): 77500',
 'Cena (CZK): 3562900, Plocha (m^2): 140706',
 'Cena (CZK): 2277550, Plocha (m^2): 77500',
 'Cena (CZK): 4566375, Plocha (m^2): 69341',
 'Cena (CZK): 3157000, Plocha (m^2): 110868',
 'Cena (CZK): 4949725, Plocha (m^2): 100912',
 'Cena (CZK): 7148350, Plocha (m^2): 103237',
 'Cena (CZK): 4059000, Plocha (m^2): 214202',
 'Cena (CZK): 5096300, Plocha (m^2): 114797',
 'Cena (CZK): 1804000, Plocha (m^2): 49600',
 'Cena (CZK): 5073750, Plocha (m^2): 167842',
 'Cena (CZK): 5502200, Plocha (m^2): 146938',
 'Cena (CZK): 2920225, Plocha (m^2): 81795',
 'Cena (CZK): 4171750, Plocha (m^2): 109157',
 'Cena (CZK): 3267495, Plocha (m^2): 109792',
 'Cena (CZK): 2421870, Plocha (m^2): 62323',
 'Cena (CZK): 2052050, Plocha (m^2): 17179',
 'Cena (CZK): 3061162, Plocha (m^2): 91224',
 'Cena (CZK): 2863850, Plocha (m^2): 92946',
 'Cena (CZK): 3078075, Plocha (m^2): 116013',
 'Cena (CZK): 2480500, Plocha (m^2): 112375',
 'Cena (CZK): 4363425, Plocha (m^2): 139931',
 'Cena (CZK): 3461425, Plocha (m^2): 48438',
 'Cena (CZK): 5524750, Plocha (m^2): 109856',
 'Cena (CZK): 2852575, Plocha (m^2): 95713',
 'Cena (CZK): 3799675, Plocha (m^2): 91816',
 'Cena (CZK): 5863000, Plocha (m^2): 172858',
 'Cena (CZK): 3923700, Plocha (m^2): 128209',
 'Cena (CZK): 3709475, Plocha (m^2): 42528',
 'Cena (CZK): 1916750, Plocha (m^2): 91170',
 'Cena (CZK): 2787180, Plocha (m^2): 86865',
 'Cena (CZK): 2478245, Plocha (m^2): 77500',
 'Cena (CZK): 2223430, Plocha (m^2): 91493',
 'Cena (CZK): 3686925, Plocha (m^2): 143806',
 'Cena (CZK): 3019445, Plocha (m^2): 77500',
 'Cena (CZK): 4617112, Plocha (m^2): 100503',
 'Cena (CZK): 4171750, Plocha (m^2): 105110',
 'Cena (CZK): 4825700, Plocha (m^2): 110481',
 'Cena (CZK): 2136612, Plocha (m^2): 117553',
 'Cena (CZK): 1871650, Plocha (m^2): 114367',
 'Cena (CZK): 2907822, Plocha (m^2): 100320',
 'Cena (CZK): 4622750, Plocha (m^2): 114130',
 'Cena (CZK): 4013900, Plocha (m^2): 99093',
 'Cena (CZK): 2682638, Plocha (m^2): 75541',
 'Cena (CZK): 4485195, Plocha (m^2): 111966',
 'Cena (CZK): 3822225, Plocha (m^2): 83506',
 'Cena (CZK): 5637500, Plocha (m^2): 100912',
 'Cena (CZK): 2255000, Plocha (m^2): 116250',
 'Cena (CZK): 2593250, Plocha (m^2): 64583',
 'Cena (CZK): 2593250, Plocha (m^2): 91493',
 'Cena (CZK): 4284500, Plocha (m^2): 126487',
 'Cena (CZK): 3087095, Plocha (m^2): 102526',
 'Cena (CZK): 4059000, Plocha (m^2): 83420',
 'Cena (CZK): 8658524, Plocha (m^2): 107262',
 'Cena (CZK): 4893350, Plocha (m^2): 226042',
 'Cena (CZK): 5851725, Plocha (m^2): 78135',
 'Cena (CZK): 3968800, Plocha (m^2): 34767',
 'Cena (CZK): 3134450, Plocha (m^2): 125034',
 'Cena (CZK): 3495250, Plocha (m^2): 91881',
 'Cena (CZK): 7216000, Plocha (m^2): 133214',
 'Cena (CZK): 3697974, Plocha (m^2): 91073',
 'Cena (CZK): 4059000, Plocha (m^2): 230918',
 'Cena (CZK): 2255000, Plocha (m^2): 65229',
 'Cena (CZK): 3066800, Plocha (m^2): 101870',
 'Cena (CZK): 3470445, Plocha (m^2): 84949',
 'Cena (CZK): 4081550, Plocha (m^2): 183449',
 'Cena (CZK): 1905475, Plocha (m^2): 72979',
 'Cena (CZK): 2886400, Plocha (m^2): 53045',
 'Cena (CZK): 1961850, Plocha (m^2): 47232',
 'Cena (CZK): 3495250, Plocha (m^2): 81698',
 'Cena (CZK): 3382500, Plocha (m^2): 96585',
 'Cena (CZK): 5096300, Plocha (m^2): 152848',
 'Cena (CZK): 5502200, Plocha (m^2): 131578',
 'Cena (CZK): 3399412, Plocha (m^2): 79524',
 'Cena (CZK): 4961000, Plocha (m^2): 73765',
 'Cena (CZK): 4059000, Plocha (m^2): 111245',
 'Cena (CZK): 3923700, Plocha (m^2): 111945',
 'Cena (CZK): 3224650, Plocha (m^2): 111460',
 'Cena (CZK): 3856050, Plocha (m^2): 119156',
 'Cena (CZK): 5186500, Plocha (m^2): 97586',
 'Cena (CZK): 5220325, Plocha (m^2): 166044',
 'Cena (CZK): 2593250, Plocha (m^2): 113021',
 'Cena (CZK): 5863000, Plocha (m^2): 125346',
 'Cena (CZK): 3743300, Plocha (m^2): 91709',
 'Cena (CZK): 4600200, Plocha (m^2): 111245',
 'Cena (CZK): 2818750, Plocha (m^2): 97952',
 'Cena (CZK): 2931500, Plocha (m^2): 27147',
 'Cena (CZK): 2367750, Plocha (m^2): 65875',
 'Cena (CZK): 5017375, Plocha (m^2): 102311',
 'Cena (CZK): 3179550, Plocha (m^2): 80729',
 'Cena (CZK): 2593250, Plocha (m^2): 67167',
 'Cena (CZK): 2751100, Plocha (m^2): 111471',
 'Cena (CZK): 8397665, Plocha (m^2): 149521',
 'Cena (CZK): 4284500, Plocha (m^2): 159338',
 'Cena (CZK): 5299250, Plocha (m^2): 145313',
 'Cena (CZK): 2818750, Plocha (m^2): 122063',
 'Cena (CZK): 1781450, Plocha (m^2): 103334',
 'Cena (CZK): 2469225, Plocha (m^2): 77500',
 'Cena (CZK): 6077225, Plocha (m^2): 129199',
 'Cena (CZK): 5747995, Plocha (m^2): 135109',
 'Cena (CZK): 7216000, Plocha (m^2): 208583',
 'Cena (CZK): 3664375, Plocha (m^2): 119695',
 'Cena (CZK): 9301875, Plocha (m^2): 147336',
 'Cena (CZK): 4961000, Plocha (m^2): 131126',
 'Cena (CZK): 2327160, Plocha (m^2): 59202',
 'Cena (CZK): 3427600, Plocha (m^2): 58125',
 'Cena (CZK): 2875125, Plocha (m^2): 108780',
 'Cena (CZK): 4284500, Plocha (m^2): 115260',
 'Cena (CZK): 7342821, Plocha (m^2): 113688',
 'Cena (CZK): 4137925, Plocha (m^2): 88738',
 'Cena (CZK): 5141400, Plocha (m^2): 179424',
 'Cena (CZK): 2897675, Plocha (m^2): 133020',
 'Cena (CZK): 4848250, Plocha (m^2): 341969',
 'Cena (CZK): 5389450, Plocha (m^2): 57113',
 'Cena (CZK): 3675650, Plocha (m^2): 109760',
 'Cena (CZK): 4149200, Plocha (m^2): 133645',
 'Cena (CZK): 5479650, Plocha (m^2): 135787',
 'Cena (CZK): 4758050, Plocha (m^2): 107951',
 'Cena (CZK): 3889875, Plocha (m^2): 146927',
 'Cena (CZK): 11316424, Plocha (m^2): 187540',
 'Cena (CZK): 2255000, Plocha (m^2): 91709',
 'Cena (CZK): 3991350, Plocha (m^2): 22787',
 'Cena (CZK): 4512255, Plocha (m^2): 81677',
 'Cena (CZK): 2706000, Plocha (m^2): 97521',
 'Cena (CZK): 4510000, Plocha (m^2): 122988',
 'Cena (CZK): 2863850, Plocha (m^2): 80062',
 'Cena (CZK): 10711250, Plocha (m^2): 247032',
 'Cena (CZK): 3901150, Plocha (m^2): 107069',
 'Cena (CZK): 3044250, Plocha (m^2): 112052',
 'Cena (CZK): 3457749, Plocha (m^2): 75541',
 'Cena (CZK): 6449300, Plocha (m^2): 52991',
 'Cena (CZK): 7103250, Plocha (m^2): 113775',
 'Cena (CZK): 4149200, Plocha (m^2): 80428',
 'Cena (CZK): 4329600, Plocha (m^2): 97058',
 'Cena (CZK): 2931500, Plocha (m^2): 27147',
 'Cena (CZK): 2863850, Plocha (m^2): 77285',
 'Cena (CZK): 3348675, Plocha (m^2): 24542',
 'Cena (CZK): 7032714, Plocha (m^2): 101353',
 'Cena (CZK): 5299250, Plocha (m^2): 273608',
 'Cena (CZK): 2345200, Plocha (m^2): 59417',
 'Cena (CZK): 6198995, Plocha (m^2): 103237',
 'Cena (CZK): 3157000, Plocha (m^2): 91988',
 'Cena (CZK): 3867325, Plocha (m^2): 108985',
 'Cena (CZK): 2525600, Plocha (m^2): 75347',
 'Cena (CZK): 3359950, Plocha (m^2): 47770',
 'Cena (CZK): 2480500, Plocha (m^2): 37674',
 'Cena (CZK): 4070275, Plocha (m^2): 127563',
 'Cena (CZK): 3244945, Plocha (m^2): 147175',
 'Cena (CZK): 3179550, Plocha (m^2): 134474',
 'Cena (CZK): 6246350, Plocha (m^2): 154613',
 'Cena (CZK): 3269750, Plocha (m^2): 88802',
 'Cena (CZK): 2209900, Plocha (m^2): 60321',
 'Cena (CZK): 4194300, Plocha (m^2): 112160',
 'Cena (CZK): 5697889, Plocha (m^2): 93000',
 'Cena (CZK): 3517800, Plocha (m^2): 146045',
 'Cena (CZK): 3647462, Plocha (m^2): 117327',
 'Cena (CZK): 3031848, Plocha (m^2): 107758',
 'Cena (CZK): 4735500, Plocha (m^2): 90955',
 'Cena (CZK): 2412850, Plocha (m^2): 106627',
 'Cena (CZK): 7024325, Plocha (m^2): 168563',
 'Cena (CZK): 3771262, Plocha (m^2): 32399',
 'Cena (CZK): 4620495, Plocha (m^2): 96768',
 'Cena (CZK): 4510000, Plocha (m^2): 86843',
 'Cena (CZK): 4056745, Plocha (m^2): 123516',
 'Cena (CZK): 2187350, Plocha (m^2): 113021',
 'Cena (CZK): 8709938, Plocha (m^2): 145011',
 'Cena (CZK): 2525600, Plocha (m^2): 18083',
 'Cena (CZK): 6539500, Plocha (m^2): 107101',
 'Cena (CZK): 2390300, Plocha (m^2): 20118',
 'Cena (CZK): 2818750, Plocha (m^2): 91719',
 'Cena (CZK): 4340875, Plocha (m^2): 34251',
 'Cena (CZK): 3337400, Plocha (m^2): 94292',
 'Cena (CZK): 9087650, Plocha (m^2): 162944',
 'Cena (CZK): 2130975, Plocha (m^2): 18083',
 'Cena (CZK): 2890910, Plocha (m^2): 114636',
 'Cena (CZK): 4882075, Plocha (m^2): 84507',
 'Cena (CZK): 2018225, Plocha (m^2): 18083',
 'Cena (CZK): 4183025, Plocha (m^2): 94432',
 'Cena (CZK): 4385975, Plocha (m^2): 101751',
 'Cena (CZK): 7170900, Plocha (m^2): 129490',
 'Cena (CZK): 2548150, Plocha (m^2): 94087',
 'Cena (CZK): 5919375, Plocha (m^2): 96875',
 'Cena (CZK): 2491775, Plocha (m^2): 41764',
 'Cena (CZK): 1781450, Plocha (m^2): 53820',
 'Cena (CZK): 2706000, Plocha (m^2): 115841',
 'Cena (CZK): 4622750, Plocha (m^2): 95584',
 'Cena (CZK): 5445825, Plocha (m^2): 111945',
 'Cena (CZK): 3089350, Plocha (m^2): 98404',
 'Cena (CZK): 3157000, Plocha (m^2): 121740',
 'Cena (CZK): 4059000, Plocha (m^2): 121815',
 'Cena (CZK): 6246350, Plocha (m^2): 1711462',
 'Cena (CZK): 1725075, Plocha (m^2): 57587',
 'Cena (CZK): 5299250, Plocha (m^2): 51129',
 'Cena (CZK): 3901150, Plocha (m^2): 90051',
 'Cena (CZK): 3562900, Plocha (m^2): 100643',
 'Cena (CZK): 3269750, Plocha (m^2): 90417',
 'Cena (CZK): 5186500, Plocha (m^2): 94055',
 'Cena (CZK): 4679125, Plocha (m^2): 94626',
 'Cena (CZK): 4961000, Plocha (m^2): 94873',
 'Cena (CZK): 5220325, Plocha (m^2): 133849',
 'Cena (CZK): 2187350, Plocha (m^2): 136723',
 'Cena (CZK): 3968800, Plocha (m^2): 207700',
 'Cena (CZK): 6223800, Plocha (m^2): 103204',
 'Cena (CZK): 3405050, Plocha (m^2): 91181',
 'Cena (CZK): 2931500, Plocha (m^2): 59202',
 'Cena (CZK): 1646150, Plocha (m^2): 56317',
 'Cena (CZK): 3957525, Plocha (m^2): 130136',
 'Cena (CZK): 4171750, Plocha (m^2): 120631',
 'Cena (CZK): 4047725, Plocha (m^2): 90417',
 'Cena (CZK): 2717275, Plocha (m^2): 74271',
 'Cena (CZK): 3337400, Plocha (m^2): 85218',
 'Cena (CZK): 5998300, Plocha (m^2): 115475',
 'Cena (CZK): 5445825, Plocha (m^2): 420912',
 'Cena (CZK): 6539500, Plocha (m^2): 126627',
 'Cena (CZK): 3134450, Plocha (m^2): 103334',
 'Cena (CZK): 2807475, Plocha (m^2): 89491',
 'Cena (CZK): 4622750, Plocha (m^2): 78189',
 'Cena (CZK): 4532550, Plocha (m^2): 98985',
 'Cena (CZK): 3179550, Plocha (m^2): 206000',
 'Cena (CZK): 9364970, Plocha (m^2): 155539',
 'Cena (CZK): 4329600, Plocha (m^2): 107693',
 'Cena (CZK): 5152675, Plocha (m^2): 121492',
 'Cena (CZK): 4171750, Plocha (m^2): 77500',
 'Cena (CZK): 4679125, Plocha (m^2): 54498',
 'Cena (CZK): 5515730, Plocha (m^2): 103463',
 'Cena (CZK): 4040960, Plocha (m^2): 86240',
 'Cena (CZK): 3713985, Plocha (m^2): 45757',
 'Cena (CZK): 3585450, Plocha (m^2): 105336',
 'Cena (CZK): 1984400, Plocha (m^2): 87457',
 'Cena (CZK): 2751100, Plocha (m^2): 105691',
 'Cena (CZK): 3463116, Plocha (m^2): 93969',
 'Cena (CZK): 5259336, Plocha (m^2): 168035',
 'Cena (CZK): 3064545, Plocha (m^2): 61214',
 'Cena (CZK): 2954050, Plocha (m^2): 122805',
 'Cena (CZK): 5299250, Plocha (m^2): 179316',
 'Cena (CZK): 3765850, Plocha (m^2): 103334',
 'Cena (CZK): 3213375, Plocha (m^2): 85433',
 'Cena (CZK): 3427600, Plocha (m^2): 147573',
 'Cena (CZK): 5389450, Plocha (m^2): 79642',
 'Cena (CZK): 3946250, Plocha (m^2): 125938',
 'Cena (CZK): 3574175, Plocha (m^2): 150695',
 'Cena (CZK): 3540350, Plocha (m^2): 169532',
 'Cena (CZK): 6020850, Plocha (m^2): 174655',
 'Cena (CZK): 4622750, Plocha (m^2): 147509',
 'Cena (CZK): 3380245, Plocha (m^2): 105486',
 'Cena (CZK): 6652250, Plocha (m^2): 197905',
 'Cena (CZK): 6898045, Plocha (m^2): 111794',
 'Cena (CZK): 5073750, Plocha (m^2): 145033',
 'Cena (CZK): 2018225, Plocha (m^2): 85250',
 'Cena (CZK): 1860375, Plocha (m^2): 132848',
 'Cena (CZK): 8118000, Plocha (m^2): 133236',
 'Cena (CZK): 3734280, Plocha (m^2): 82721',
 'Cena (CZK): 2976600, Plocha (m^2): 86111',
 'Cena (CZK): 2703745, Plocha (m^2): 83959',
 'Cena (CZK): 8456250, Plocha (m^2): 2316878',
 'Cena (CZK): 4013900, Plocha (m^2): 103334',
 'Cena (CZK): 4250675, Plocha (m^2): 83905',
 'Cena (CZK): 5863000, Plocha (m^2): 139985',
 'Cena (CZK): 6088500, Plocha (m^2): 96875',
 'Cena (CZK): 5863000, Plocha (m^2): 106563',
 'Cena (CZK): 4228125, Plocha (m^2): 151933',
 'Cena (CZK): 7726600, Plocha (m^2): 175010',
 'Cena (CZK): 7982700, Plocha (m^2): 130233',
 'Cena (CZK): 6787550, Plocha (m^2): 111729',
 'Cena (CZK): 2845246, Plocha (m^2): 62646',
 'Cena (CZK): 5457100, Plocha (m^2): 121363',
 'Cena (CZK): 1961850, Plocha (m^2): 53820',
 'Cena (CZK): 7306200, Plocha (m^2): 116745',
 'Cena (CZK): 3275388, Plocha (m^2): 124861',
 'Cena (CZK): 4836975, Plocha (m^2): 127961',
 'Cena (CZK): 1758900, Plocha (m^2): 68911',
 'Cena (CZK): 2683450, Plocha (m^2): 114356',
 'Cena (CZK): 3134450, Plocha (m^2): 88006',
 'Cena (CZK): 6404200, Plocha (m^2): 114689',
 'Cena (CZK): 4667850, Plocha (m^2): 88243',
 'Cena (CZK): 4329600, Plocha (m^2): 97327',
 'Cena (CZK): 5162822, Plocha (m^2): 1772385',
 'Cena (CZK): 8510956, Plocha (m^2): 152385',
 'Cena (CZK): 4825700, Plocha (m^2): 98328',
 'Cena (CZK): 4566375, Plocha (m^2): 152256',
 'Cena (CZK): 3495250, Plocha (m^2): 133472',
 'Cena (CZK): 4575395, Plocha (m^2): 152751',
 'Cena (CZK): 1849100, Plocha (m^2): 90417',
 'Cena (CZK): 1973125, Plocha (m^2): 91967',
 'Cena (CZK): 5998300, Plocha (m^2): 95250',
 'Cena (CZK): 1916750, Plocha (m^2): 27900',
 'Cena (CZK): 3161510, Plocha (m^2): 69266',
 'Cena (CZK): 3416325, Plocha (m^2): 137477',
 'Cena (CZK): 3551625, Plocha (m^2): 189445',
 'Cena (CZK): 3472700, Plocha (m^2): 26350',
 'Cena (CZK): 9857823, Plocha (m^2): 219917',
 'Cena (CZK): 7172276, Plocha (m^2): 84174',
 'Cena (CZK): 4284500, Plocha (m^2): 56737',
 'Cena (CZK): 2142250, Plocha (m^2): 97779',
 'Cena (CZK): 2388045, Plocha (m^2): 91709',
 'Cena (CZK): 3157000, Plocha (m^2): 90417',
 'Cena (CZK): 4002625, Plocha (m^2): 121083',
 'Cena (CZK): 3901150, Plocha (m^2): 99545',
 'Cena (CZK): 3021700, Plocha (m^2): 45467',
 'Cena (CZK): 2931500, Plocha (m^2): 74594',
 'Cena (CZK): 6314000, Plocha (m^2): 129285',
 'Cena (CZK): 3517800, Plocha (m^2): 81160',
 'Cena (CZK): 3269750, Plocha (m^2): 98425',
 'Cena (CZK): 4476175, Plocha (m^2): 78587',
 'Cena (CZK): 2660900, Plocha (m^2): 18083',
 'Cena (CZK): 4284500, Plocha (m^2): 202362',
 'Cena (CZK): 3314850, Plocha (m^2): 115066',
 'Cena (CZK): 3585450, Plocha (m^2): 102257',
 'Cena (CZK): 3720750, Plocha (m^2): 98490',
 'Cena (CZK): 2976600, Plocha (m^2): 83959',
 'Cena (CZK): 3653100, Plocha (m^2): 105809',
 'Cena (CZK): 3887620, Plocha (m^2): 87414',
 'Cena (CZK): 3031442, Plocha (m^2): 184278',
 'Cena (CZK): 2818750, Plocha (m^2): 77231',
 'Cena (CZK): 2773650, Plocha (m^2): 114463',
 'Cena (CZK): 4949725, Plocha (m^2): 88264',
 'Cena (CZK): 1375550, Plocha (m^2): 107854',
 'Cena (CZK): 3337400, Plocha (m^2): 95218',
 'Cena (CZK): 7667000, Plocha (m^2): 119942',
 'Cena (CZK): 8894442, Plocha (m^2): 122644',
 'Cena (CZK): 4036450, Plocha (m^2): 87435',
 'Cena (CZK): 2863850, Plocha (m^2): 53820',
 'Cena (CZK): 4233762, Plocha (m^2): 77500',
 'Cena (CZK): 4814425, Plocha (m^2): 99512',
 'Cena (CZK): 1713800, Plocha (m^2): 96875',
 'Cena (CZK): 5412000, Plocha (m^2): 571639',
 'Cena (CZK): 4329600, Plocha (m^2): 34251',
 'Cena (CZK): 1826550, Plocha (m^2): 90524',
 'Cena (CZK): 2818750, Plocha (m^2): 77500',
 'Cena (CZK): 4307050, Plocha (m^2): 100987',
 'Cena (CZK): 9606300, Plocha (m^2): 134269',
 'Cena (CZK): 2683450, Plocha (m^2): 90471',
 'Cena (CZK): 4848250, Plocha (m^2): 131417',
 'Cena (CZK): 2401575, Plocha (m^2): 89760',
 'Cena (CZK): 2255000, Plocha (m^2): 80148',
 'Cena (CZK): 2457950, Plocha (m^2): 109081',
 'Cena (CZK): 2908950, Plocha (m^2): 103021',
 'Cena (CZK): 2773650, Plocha (m^2): 77500',
 'Cena (CZK): 3822225, Plocha (m^2): 81698',
 'Cena (CZK): 1510850, Plocha (m^2): 96520',
 'Cena (CZK): 5434550, Plocha (m^2): 87457',
 'Cena (CZK): 5536025, Plocha (m^2): 161060',
 'Cena (CZK): 3720524, Plocha (m^2): 94367',
 'Cena (CZK): 2435400, Plocha (m^2): 109792',
 'Cena (CZK): 5817900, Plocha (m^2): 130136',
 'Cena (CZK): 3788400, Plocha (m^2): 111557',
 'Cena (CZK): 3382500, Plocha (m^2): 107542',
 'Cena (CZK): 2593250, Plocha (m^2): 112806',
 'Cena (CZK): 3991350, Plocha (m^2): 167659',
 'Cena (CZK): 6314000, Plocha (m^2): 152352',
 'Cena (CZK): 7661362, Plocha (m^2): 116250',
 'Cena (CZK): 1353000, Plocha (m^2): 103021',
 'Cena (CZK): 3269750, Plocha (m^2): 372969',
 'Cena (CZK): 5006100, Plocha (m^2): 47393',
 'Cena (CZK): 2593250, Plocha (m^2): 96445',
 'Cena (CZK): 5141400, Plocha (m^2): 120857',
 'Cena (CZK): 4084572, Plocha (m^2): 95788',
 'Cena (CZK): 3371225, Plocha (m^2): 84432',
 'Cena (CZK): 5389450, Plocha (m^2): 241327',
 'Cena (CZK): 2841300, Plocha (m^2): 87834',
 'Cena (CZK): 3202100, Plocha (m^2): 90955',
 'Cena (CZK): 4652065, Plocha (m^2): 75993',
 'Cena (CZK): 4848250, Plocha (m^2): 179058',
 'Cena (CZK): 2548150, Plocha (m^2): 234115',
 'Cena (CZK): 7103250, Plocha (m^2): 99028',
 'Cena (CZK): 3134450, Plocha (m^2): 96875',
 'Cena (CZK): 3044250, Plocha (m^2): 36360',
 'Cena (CZK): 6201250, Plocha (m^2): 137778',
 'Cena (CZK): 2458130, Plocha (m^2): 92494',
 'Cena (CZK): 4406270, Plocha (m^2): 72786',
 'Cena (CZK): 3946250, Plocha (m^2): 123322',
 'Cena (CZK): 1925770, Plocha (m^2): 18083',
 'Cena (CZK): 1801745, Plocha (m^2): 60127',
 'Cena (CZK): 2762375, Plocha (m^2): 20667',
 'Cena (CZK): 4081550, Plocha (m^2): 116670',
 'Cena (CZK): 1826550, Plocha (m^2): 20344',
 'Cena (CZK): 4780600, Plocha (m^2): 114819',
 'Cena (CZK): 2615800, Plocha (m^2): 47361',
 'Cena (CZK): 2683450, Plocha (m^2): 64583',
 'Cena (CZK): 2037392, Plocha (m^2): 46070',

## Export do souboru

Analogicky s načtením dat, nejčastěji použijeme [`to_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) (ovšem voláme tuto metodu na `DataFrame`, který chceme uložit), ale jsou i [dálší funkce](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)

In [24]:
# Pokud nechceme mít zapisovat inde, nastavíme index=False
houses.to_csv('houses_processed.csv', index=False)